import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { TITLE } from '@/config';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, 'min-h-dvh')}>
        <header className="border-b h-16 flex items-center px-6">
          <Button variant="ghost" asChild>
            <Link href="/">{TITLE}</Link>
          </Button>
        </header>

        <main className="container py-8">{children}</main>

        <footer className="border-t sticky top-full h-16 flex items-center px-6">
          <p>&copy; {TITLE}.</p>
        </footer>
      </body>
    </html>
  );
}
